name: Deploy on Heroku

on:
  push:
    branches:
      - master
    path:
      - 'client/**'
      - 'backend/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mern-ws-chat"
          heroku_email: "maciejro.krawczyk@gmail.com"
          usedocker: true
          docker_build_args: |
            REACT_APP_PUBLIC_VAPID_KEY
        env:
          REACT_APP_PUBLIC_VAPID_KEY: ${{ secrets.REACT_APP_PUBLIC_VAPID_KEY }}
