name: CI-backend

on:
  push:
    path:
      - 'backend/**'
    branches: [ master ]
  pull_request:
    path:
      - 'backend/**'
    branches: [ master ]

  workflow_dispatch:

jobs:
  buildBackend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
#       - run: npm test
